#' Create Google Sheets API format requests
#'
#' Generates Google Sheets API requests to apply custom formatting to table data
#' columns.
#'
#' @param tbl A table created with tablespan::tablespan containing format
#' specifications in the tbl$formats$columns element
#' @param google_sheet Google Sheet spreadsheet dribble created with
#' googlesheets4::gs4_get()
#' @param sheet Name of the sheet where the table is being written
#' @param locations A list containing the row and column positions of table
#' elements, generated by get_locations()
#' @return A list of Google Sheets API requests that can be used to apply
#' custom formatting to table data columns
#' @noRd
format_requests_googlesheet <- function(
  tbl,
  google_sheet,
  sheet,
  locations
) {
  require_googlesheets4()
  formats <- get_formats_googlesheet(tbl = tbl)
  format_requests <- list()
  # Add user defined formats
  column_formats <- formats$columns
  for (column_name in names(column_formats)) {
    for (format in column_formats[[column_name]]) {
      if (is.null(format$googlesheet)) {
        next
      } else {
        if (is.null(format$rows)) {
          data_rows <- c(
            locations$row$start_row_data,
            (locations$row$end_row_data)
          )
          contiguous_rows <- TRUE
        } else {
          data_rows <- (locations$row$start_row_data + format$rows) - 1
          if (
            all(min(data_rows):max(data_rows) %in% data_rows) &
              all(data_rows %in% min(data_rows):max(data_rows))
          ) {
            data_rows <- c(min(data_rows), max(data_rows))
            contiguous_rows <- TRUE
          } else {
            contiguous_rows <- FALSE
          }
        }
        data_cols <- locations$col$start_col_header_lhs +
          which(names(column_formats) == column_name) -
          1
        if (is(format$googlesheet, "gs_format")) {
          if (contiguous_rows) {
            format_requests[[
              length(format_requests) + 1
            ]] <- gs_create_style_request(
              sheetId = google_sheet$sheets$id[
                google_sheet$sheets$name == sheet
              ],
              row = data_rows,
              col = data_cols,
              format = format$googlesheet
            )
          } else {
            for (rw in data_rows) {
              format_requests[[
                length(format_requests) + 1
              ]] <- gs_create_style_request(
                sheetId = google_sheet$sheets$id[
                  google_sheet$sheets$name == sheet
                ],
                row = rw,
                col = data_cols,
                format = format$googlesheet
              )
            }
          }
        }
      }
    }
  }
  return(format_requests)
}

get_formats_googlesheet <- function(tbl) {
  require_googlesheets4()

  formats <- list()
  force(tbl)
  data <- get_table_data(tbl)

  for (column_name in colnames(data)) {
    for (form in tbl$formats$columns[[column_name]]) {
      if (form$fmt$type == "number") {
        # We need to create a new environment for each function
        # here because NSE messes up the variables
        formats$columns[[column_name]][[
          length(formats$columns[[column_name]]) + 1
        ]] <- local({
          num_form <- format_number_googlesheet(
            decimals = form$fmt$args$decimals,
            sep_mark = form$fmt$args$sep_mark,
            dec_mark = form$fmt$args$dec_mark
          )
          list(
            googlesheet = num_form,
            rows = form$row
          )
        })
      } else if (form$fmt$type == "text") {
        formats$columns[[column_name]][[
          length(formats$columns[[column_name]]) + 1
        ]] <- list(
          googlesheet = format_text_googlesheet(),
          rows = form$row
        )
      } else if (form$fmt$type == "date") {
        # Create a new environment for each function
        formats$columns[[column_name]][[
          length(formats$columns[[column_name]]) + 1
        ]] <- local({
          list(
            googlesheet = format_date_googlesheet(),
            rows = form$row
          )
        })
      } else {
        formats$columns[[column_name]][[
          length(formats$columns[[column_name]]) + 1
        ]] <- local({
          list(
            googlesheet = NULL,
            rows = form$row
          )
        })
      }
    }
  }

  return(formats)
}

format_text_googlesheet <- function() {
  return(create_format_googlesheet(type = "TEXT", pattern = number_format))
}

format_date_googlesheet <- function() {
  return(create_format_googlesheet(type = "DATE", pattern = number_format))
}

#' format_number_googlesheet
#'
#' Creates an googlesheet number format string for formatting numbers with specified decimal places,
#' thousands separator, and decimal mark.
#'
#' @param decimals number of decimal places to display
#' @param sep_mark character used as thousands separator (default: ",")
#' @param dec_mark character used as decimal mark (default: ".")
#'
#' @returns a character string representing the googlesheet number format, or NULL if googlesheet is not available
#' @noRd
format_number_googlesheet <- function(decimals, sep_mark, dec_mark) {
  if (decimals == 0) {
    googlesheets_format <- "0"
  } else {
    googlesheets_format <- paste0(ifelse(
      sep_mark == "",
      paste0("0", dec_mark, paste0(rep("0", decimals), collapse = "")),
      paste0(
        "#",
        sep_mark,
        "##0",
        dec_mark,
        paste0(rep("0", decimals), collapse = "")
      )
    ))
  }

  return(create_format_googlesheet(
    type = "NUMBER",
    pattern = googlesheets_format
  ))
}


#' create_format_googlesheet
#'
#' Create a Google Sheets formatting specification for tablespan exports.
#'
#' @param type The type of formatting to apply. Must be one of:
#'   "TEXT", "NUMBER", "PERCENT", "CURRENCY", "DATE", "TIME", "DATE_TIME", or "SCIENTIFIC".
#'   When NULL, no formatting will be applied.
#' @param pattern A custom pattern string for number formatting. This follows Google Sheets'
#'   formatting rules. When NULL, a default pattern will be used based on the type.
#'
#' @returns A list with class "gs_format" containing the formatting specification,
#'   or NULL if type is NULL. This object can be passed to format_column() via the
#'   format_googlesheet parameter.
#'
#' @details
#' The returned format specification will be applied when exporting to Google Sheets.
#' For number formatting, the pattern parameter follows Google Sheets' number format
#' syntax. For example, "#,##0.00" would format numbers with thousands separators
#' and two decimal places.
#'
#' @export
#' @examples
#' # Create a number format with 2 decimal places
#' num_format <- create_format_googlesheet(type = "NUMBER", pattern = "#,##0.00")
#'
#' # Create a percentage format
#' percent_format <- create_format_googlesheet(type = "PERCENT")
#'
#' # Apply to a tablespan table
#' library(tablespan)
#' library(dplyr)
#' data("mtcars")
#'
#' summarized_table <- mtcars |>
#'   group_by(cyl) |>
#'   summarise(mpg = mean(mpg))
#'
#' tbl <- tablespan(data = summarized_table,
#'                  formula = Cylinder:cyl ~ MPG:mpg)
#'
#' tbl |>
#'   format_column(columns = mpg,
#'                 format_googlesheet = num_format)
create_format_googlesheet <- function(
  type = c(
    "TEXT",
    "NUMBER",
    "PERCENT",
    "CURRENCY",
    "DATE",
    "TIME",
    "DATE_TIME",
    "SCIENTIFIC"
  ),
  pattern = NULL
) {
  if (is.null(type)) {
    return(NULL)
  }
  gs_format <- list(
    type = match.arg(type),
    pattern = pattern
  )
  class(gs_format) <- "gs_format"
  return(
    gs_format
  )
}
